kind: Secret
apiVersion: v1
metadata:
  name: dotfile-secret
#Defines the type of Secret? means-->Generic key-value secret (default type).  
type: Opaque 
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=

#Secret means this object stores sensitive data (passwords, tokens, keys, etc.).
#echo -n "admin" | base64
#echo "YWRtaw4=" | base64 --decode
#echo -n "admin123"  | base64