apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 80  # container port
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
