apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort          # ✅ FIX 1
  selector:               # ✅ FIX 2 (match pod labels)
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080     # optional
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-np
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
