apiVersion: v1
kind: pod
metadata:
 name: sa-demo
 namespace: expense
spec:
 serviceAccount: expense-mysql-secret 
 initContainers:
 - name: awscli
   image: amazon/aws-cli 
   command: ['sh', '-c', 'aws secretsmanager get-secret-value  
    --secret-id expense/mysql/creds --query SecretString --output text > ']
   volumeMounts:
   - mountPath: /secrets
     name: secret-volume
 containers:
   - name: nginx
     image: nginx  
     volumeMounts:
     - mountPath: /secrets
       name: secret-volume
    volumes:
    - name: secret-volume
      emptyDir: {}   
